// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddOAuthAccount(arg1) {
  return window['go']['desktop']['App']['AddOAuthAccount'](arg1);
}

export function AddPasswordAccount(arg1) {
  return window['go']['desktop']['App']['AddPasswordAccount'](arg1);
}

export function AllowDomainImages(arg1) {
  return window['go']['desktop']['App']['AllowDomainImages'](arg1);
}

export function AppVersion() {
  return window['go']['desktop']['App']['AppVersion']();
}

export function ArchiveMessage(arg1) {
  return window['go']['desktop']['App']['ArchiveMessage'](arg1);
}

export function CancelDownload() {
  return window['go']['desktop']['App']['CancelDownload']();
}

export function CancelSend(arg1) {
  return window['go']['desktop']['App']['CancelSend'](arg1);
}

export function CheckForUpdates() {
  return window['go']['desktop']['App']['CheckForUpdates']();
}

export function ClearSentOutbox() {
  return window['go']['desktop']['App']['ClearSentOutbox']();
}

export function ConfirmThemeImport(arg1, arg2) {
  return window['go']['desktop']['App']['ConfirmThemeImport'](arg1, arg2);
}

export function DeleteAccount(arg1) {
  return window['go']['desktop']['App']['DeleteAccount'](arg1);
}

export function DeleteAddress(arg1) {
  return window['go']['desktop']['App']['DeleteAddress'](arg1);
}

export function DeleteDraft(arg1) {
  return window['go']['desktop']['App']['DeleteDraft'](arg1);
}

export function DeleteMessage(arg1) {
  return window['go']['desktop']['App']['DeleteMessage'](arg1);
}

export function DeleteSignature(arg1) {
  return window['go']['desktop']['App']['DeleteSignature'](arg1);
}

export function DeleteTheme(arg1) {
  return window['go']['desktop']['App']['DeleteTheme'](arg1);
}

export function DiscoverConfig(arg1) {
  return window['go']['desktop']['App']['DiscoverConfig'](arg1);
}

export function DownloadMessageOffline(arg1) {
  return window['go']['desktop']['App']['DownloadMessageOffline'](arg1);
}

export function DownloadRange(arg1, arg2) {
  return window['go']['desktop']['App']['DownloadRange'](arg1, arg2);
}

export function ExportData(arg1, arg2) {
  return window['go']['desktop']['App']['ExportData'](arg1, arg2);
}

export function ExportMessagePrintView(arg1) {
  return window['go']['desktop']['App']['ExportMessagePrintView'](arg1);
}

export function ExportTheme(arg1) {
  return window['go']['desktop']['App']['ExportTheme'](arg1);
}

export function GetAccountSignatures(arg1) {
  return window['go']['desktop']['App']['GetAccountSignatures'](arg1);
}

export function GetMessage(arg1) {
  return window['go']['desktop']['App']['GetMessage'](arg1);
}

export function GetMessageHTML(arg1, arg2) {
  return window['go']['desktop']['App']['GetMessageHTML'](arg1, arg2);
}

export function ListSystemFonts() {
  return window['go']['desktop']['App']['ListSystemFonts']();
}

export function GetMessageSource(arg1) {
  return window['go']['desktop']['App']['GetMessageSource'](arg1);
}

export function GetSetting(arg1) {
  return window['go']['desktop']['App']['GetSetting'](arg1);
}

export function GetThemeApply(arg1) {
  return window['go']['desktop']['App']['GetThemeApply'](arg1);
}

export function GetUIPrefs() {
  return window['go']['desktop']['App']['GetUIPrefs']();
}

export function ImportData(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['ImportData'](arg1, arg2, arg3);
}

export function InspectBackupFile() {
  return window['go']['desktop']['App']['InspectBackupFile']();
}

export function IsDemoMode() {
  return window['go']['desktop']['App']['IsDemoMode']();
}

export function IsDevMode() {
  return window['go']['desktop']['App']['IsDevMode']();
}

export function Licenses() {
  return window['go']['desktop']['App']['Licenses']();
}

export function ListAccounts() {
  return window['go']['desktop']['App']['ListAccounts']();
}

export function ListAddresses() {
  return window['go']['desktop']['App']['ListAddresses']();
}

export function ListDrafts() {
  return window['go']['desktop']['App']['ListDrafts']();
}

export function ListFolders(arg1) {
  return window['go']['desktop']['App']['ListFolders'](arg1);
}

export function ListImageAllowlist() {
  return window['go']['desktop']['App']['ListImageAllowlist']();
}

export function ListMessages(arg1) {
  return window['go']['desktop']['App']['ListMessages'](arg1);
}

export function ListOAuthProviders() {
  return window['go']['desktop']['App']['ListOAuthProviders']();
}

export function ListOutbox() {
  return window['go']['desktop']['App']['ListOutbox']();
}

export function ListSignatures() {
  return window['go']['desktop']['App']['ListSignatures']();
}

export function ListThemes() {
  return window['go']['desktop']['App']['ListThemes']();
}

export function ListUnifiedViews() {
  return window['go']['desktop']['App']['ListUnifiedViews']();
}

export function MoveMessage(arg1, arg2) {
  return window['go']['desktop']['App']['MoveMessage'](arg1, arg2);
}

export function PreviewThemeImport() {
  return window['go']['desktop']['App']['PreviewThemeImport']();
}

export function ProgramLicense() {
  return window['go']['desktop']['App']['ProgramLicense']();
}

export function ReadAttachment(arg1, arg2) {
  return window['go']['desktop']['App']['ReadAttachment'](arg1, arg2);
}

export function RebuildMenu() {
  return window['go']['desktop']['App']['RebuildMenu']();
}

export function RemoveImageAllow(arg1, arg2) {
  return window['go']['desktop']['App']['RemoveImageAllow'](arg1, arg2);
}

export function RemoveOffline(arg1) {
  return window['go']['desktop']['App']['RemoveOffline'](arg1);
}

export function ResumePendingDownload() {
  return window['go']['desktop']['App']['ResumePendingDownload']();
}

export function SaveAllAttachments(arg1) {
  return window['go']['desktop']['App']['SaveAllAttachments'](arg1);
}

export function SaveAttachment(arg1, arg2) {
  return window['go']['desktop']['App']['SaveAttachment'](arg1, arg2);
}

export function SaveDraft(arg1, arg2) {
  return window['go']['desktop']['App']['SaveDraft'](arg1, arg2);
}

export function SaveSignature(arg1) {
  return window['go']['desktop']['App']['SaveSignature'](arg1);
}

export function Search(arg1) {
  return window['go']['desktop']['App']['Search'](arg1);
}

export function SearchAddresses(arg1, arg2) {
  return window['go']['desktop']['App']['SearchAddresses'](arg1, arg2);
}

export function SendMessage(arg1) {
  return window['go']['desktop']['App']['SendMessage'](arg1);
}

export function SenderPhotos(arg1) {
  return window['go']['desktop']['App']['SenderPhotos'](arg1);
}

export function SetAccountSignatures(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['SetAccountSignatures'](arg1, arg2, arg3);
}

export function SetFlagColor(arg1, arg2) {
  return window['go']['desktop']['App']['SetFlagColor'](arg1, arg2);
}

export function SetFlagged(arg1, arg2) {
  return window['go']['desktop']['App']['SetFlagged'](arg1, arg2);
}

export function SetMailActionsEnabled(arg1) {
  return window['go']['desktop']['App']['SetMailActionsEnabled'](arg1);
}

export function SetSeen(arg1, arg2) {
  return window['go']['desktop']['App']['SetSeen'](arg1, arg2);
}

export function SetSetting(arg1, arg2) {
  return window['go']['desktop']['App']['SetSetting'](arg1, arg2);
}

export function SetWindowTheme(arg1) {
  return window['go']['desktop']['App']['SetWindowTheme'](arg1);
}

export function SetWindowTitle(arg1) {
  return window['go']['desktop']['App']['SetWindowTitle'](arg1);
}

export function SnoozeMessage(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['SnoozeMessage'](arg1, arg2, arg3);
}

export function SystemColorScheme() {
  return window['go']['desktop']['App']['SystemColorScheme']();
}

export function TestConnection(arg1) {
  return window['go']['desktop']['App']['TestConnection'](arg1);
}

export function TriggerSync() {
  return window['go']['desktop']['App']['TriggerSync']();
}

export function TrustSenderImages(arg1) {
  return window['go']['desktop']['App']['TrustSenderImages'](arg1);
}

export function UnarchiveMessage(arg1, arg2) {
  return window['go']['desktop']['App']['UnarchiveMessage'](arg1, arg2);
}

export function UndoDelete(arg1) {
  return window['go']['desktop']['App']['UndoDelete'](arg1);
}

export function UnsnoozeMessage(arg1) {
  return window['go']['desktop']['App']['UnsnoozeMessage'](arg1);
}

export function UpdateAccount(arg1) {
  return window['go']['desktop']['App']['UpdateAccount'](arg1);
}
