// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function AddOAuthAccount(arg1:desktop.AddAccountRequest):Promise<desktop.AccountDTO>;

export function AddPasswordAccount(arg1:desktop.AddAccountRequest):Promise<desktop.AccountDTO>;

export function AllowDomainImages(arg1:number):Promise<void>;

export function AppVersion():Promise<string>;

export function CancelSend(arg1:number):Promise<boolean>;

export function ClearSentOutbox():Promise<void>;

export function DeleteDraft(arg1:number):Promise<void>;

export function DeleteMessage(arg1:number):Promise<void>;

export function DeleteSignature(arg1:number):Promise<void>;

export function DiscoverConfig(arg1:string):Promise<desktop.DiscoveredDTO>;

export function ExportMessagePrintView(arg1:number):Promise<void>;

export function GetAccountSignatures(arg1:number):Promise<desktop.AccountSignaturesDTO>;

export function GetMessage(arg1:number):Promise<desktop.MessageDetailDTO>;

export function GetMessageHTML(arg1:number,arg2:boolean):Promise<string>;

export function GetSetting(arg1:string):Promise<desktop.SettingResult>;

export function GetUIPrefs():Promise<desktop.UIPrefsDTO>;

export function Licenses():Promise<string>;

export function ListAccounts():Promise<Array<desktop.AccountDTO>>;

export function ListDrafts():Promise<Array<desktop.DraftDTO>>;

export function ListFolders(arg1:number):Promise<Array<desktop.FolderDTO>>;

export function ListMessages(arg1:desktop.ListMessagesRequest):Promise<desktop.MessageListDTO>;

export function ListOAuthProviders():Promise<Record<string, string>>;

export function ListOutbox():Promise<Array<desktop.OutboxRowDTO>>;

export function ListSignatures():Promise<Array<desktop.SignatureDTO>>;

export function ListUnifiedViews():Promise<Array<desktop.UnifiedViewDTO>>;

export function ProgramLicense():Promise<string>;

export function SaveAttachment(arg1:number,arg2:number):Promise<string>;

export function SaveDraft(arg1:number,arg2:desktop.ComposeRequest):Promise<number>;

export function SaveSignature(arg1:desktop.SignatureDTO):Promise<desktop.SignatureDTO>;

export function Search(arg1:desktop.SearchRequestDTO):Promise<Array<desktop.MessageSummaryDTO>>;

export function SendMessage(arg1:desktop.ComposeRequest):Promise<number>;

export function SenderPhotos(arg1:string):Promise<Array<string>>;

export function SetAccountSignatures(arg1:number,arg2:number,arg3:number):Promise<void>;

export function SetFlagged(arg1:number,arg2:boolean):Promise<void>;

export function SetSeen(arg1:number,arg2:boolean):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function TestConnection(arg1:desktop.TestConnectionRequest):Promise<void>;

export function TriggerSync():Promise<void>;

export function TrustSenderImages(arg1:number):Promise<void>;
